# Email Alert Configuration for Coolie (Tamil) Ticket Monitoring

# Email settings
email:
  smtp_server: smtp.gmail.com
  smtp_port: 587
  from_email: raja.arun91@gmail.com
  to_email: arunrajadh@gmail.com
  password: psalkdurpulbemep
  
# Check interval in minutes
check_interval_minutes: 30

# Platforms to monitor
platforms:
  - name: "BookMyShow"
    url: "https://in.bookmyshow.com/movies/bengaluru/coolie/ET00395817"
    selector: "button[data-phase='postRelease'], .sc-qswwm9-0, .notify-me-btn, .book-tickets"
    detection_method: "element_exists"
    keywords: ["book", "tickets", "notify me"]
    
  - name: "PVR Cinemas"
    url: "https://www.pvrcinemas.com/coming-soon"
    selector: ".movie-tile, .cinema-movie-card, .book-now"
    detection_method: "text_contains"
    keywords: ["coolie", "book now", "tickets"]
    
  - name: "District (Paytm)"
    url: "https://paytm.com/movies/coolie-movie-detail-172677"
    selector: ".book-ticket, .cta-button, .movie-card"
    detection_method: "text_contains" 
    keywords: ["book ticket", "buy now", "book", "available"]

# Logging settings
logging:
  level: INFO
  file: ticket_alert.log