# Cloud-friendly configuration for Coolie movie monitoring
# This config focuses on platforms that work reliably from GitHub Actions/cloud servers

# Email settings
email:
  smtp_server: smtp.gmail.com
  smtp_port: 587
  from_email: ENV:EMAIL_FROM
  to_email: ENV:EMAIL_TO
  password: ENV:EMAIL_PASSWORD

# Check interval in minutes
check_interval_minutes: 30

# Platforms that work well from cloud servers
platforms:
  # District/Paytm works well from cloud
  - name: "District (Paytm)"
    url: "https://paytm.com/movies/coolie-movie-detail-172677"
    selector: ".book-ticket, .cta-button, .movie-card, .btn-book"
    detection_method: "text_contains"
    keywords: ["book ticket", "buy now", "book", "available"]
  
  # Alternative: Try BookMyShow API endpoint (sometimes works better)
  - name: "BookMyShow API Check"
    url: "https://in.bookmyshow.com/api/movies/coolie/ET00395817"
    selector: "body"
    detection_method: "text_contains"
    keywords: ["book", "available", "show"]
  
  # Try mobile version (sometimes has different blocking rules)
  - name: "BookMyShow Mobile"
    url: "https://m.bookmyshow.com/movies/bengaluru/coolie/ET00395817"
    selector: ".book-button, .notify-me"
    detection_method: "text_contains"
    keywords: ["book", "tickets"]

# Logging settings
logging:
  level: INFO
  file: ticket_alert.log