name: Coolie Ticket Monitor

on:
  schedule:
    # Run every 5 minutes during likely booking hours (9 AM to 11 PM IST)
    - cron: '*/5 3-17 * * *'  # 9 AM to 11 PM IST (UTC+5:30)
  workflow_dispatch:  # Allow manual triggering

jobs:
  monitor-tickets:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Coolie ticket monitor
      env:
        EMAIL_SMTP_SERVER: ${{ secrets.EMAIL_SMTP_SERVER }}
        EMAIL_SMTP_PORT: ${{ secrets.EMAIL_SMTP_PORT }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
      run: |
        echo "🎬 Starting Coolie PVR ticket monitor..."
        echo "Target screens: PVR Soul Spirit, PVR Centro Mall, PVR Nexus Koramangala, PVR Felicity Mall"
        python bookmyshow_monitor.py --once
    
    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: monitor-logs-${{ github.run_number }}
        path: |
          *.log
          *.html
        retention-days: 7
