name: Coolie Ticket Monitor

on:
  schedule:
    # Run every 30 minutes from 9 AM to 11 PM IST (3:30 AM to 5:30 PM UTC)
    - cron: '*/30 3-17 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  check-tickets:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run ticket check
      env:
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        python ticket_alert.py --once
    
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: ticket-logs
        path: ticket_alert.log
        retention-days: 7