name: Simple Ticket Monitor (CloudScraper)

on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  check-tickets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 python-dotenv cloudscraper lxml
    
    - name: Run CloudScraper Monitor
      env:
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_USER: ${{ secrets.EMAIL_FROM }}
      run: |
        echo "🎬 Starting Coolie Ticket Monitor..."
        echo "Using CloudScraper to bypass anti-bot protection"
        python bookmyshow_cloudscraper.py
    
    - name: Status Report
      if: always()
      run: |
        echo "✅ Monitoring check completed"
        echo "Check your email for any ticket alerts"